version: 2.1
jobs:
  build:
    docker:
      - image: g33tha/plugin:test
        environment:
           version_number: $CIRCLE_BRANCH
     
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          
      - run: git clone https://github.com/project-sunbird/sunbird-content-plugins.git plugins -b $CIRCLE_BRANCH 
      - run: npm install
      - run: cd app && bower cache clean --allow-root
      - run: cd app && bower install --force --allow-root
      - run: npm run collection-plugins
      - run: npm run build
      - run: 
          name: test-with-coverage
          command: 'mkdir -p /tmp/logs && npm run test-with-coverage | tee /tmp/logs/test_cases.log'
      - run:
          name: Publishing report to Codacy
          command: 'cat ./coverage/lcov.info | codacy-coverage '
          when: always
       
      - store_artifacts:
          path: /tmp/logs
          destination: logs
          
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
