version: 2.1
jobs:
  build:
    working_directory: ~/collection-editor
    docker:
      - image: circleci/node:6.10-browsers
        environment:
           version_number: $CIRCLE_BRANCH
     
    steps:
      - checkout:
          path: ~/collection-editor
      
      #- restore_cache:
          #key: dependency-cache-{{ checksum "package.json" }}
       
      - run:
          name: clone plugins
          command: |
            prnumber=$(echo $CI_PULL_REQUEST | awk -F'/' '{print $NF}')
            prdata=$(curl -X GET -u $GITHUB_USER_TOKEN:x-oauth-basic https://api.github.com/repos/project-sunbird/sunbird-collection-editor/pulls/$prnumber)
            target_branch=$(echo "${prdata}" | jq -r '.base.ref')
            git clone https://github.com/project-sunbird/sunbird-content-plugins.git plugins -b $target_branch 
       
      #- run: git clone https://github.com/project-sunbird/sunbird-content-plugins.git plugins -b $CIRCLE_BRANCH 

      - run: sudo npm install -g bower@1.8.0 grunt-cli@1.2.0 gulp@3.9.1 codacy-coverage
      - run: npm install
      - run: cd app && bower cache clean --allow-root
      - run: cd app && bower install --force --allow-root
      - run: npm run collection-plugins
      - run: npm run build
      
      - run: 
          name: test-with-coverage
          command: 'npm run test-with-coverage'
          
      - run: mkdir -p /tmp/coverage && cp ./coverage/lcov.info /tmp/coverage
      
      - run:
          name: Publishing report to Codacy
          command: 'cat ./coverage/lcov.info | codacy-coverage '
          when: always
       
      - store_artifacts:
          path: /tmp/coverage
          destination: coverage
      
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
